#!/usr/bin/env python3
"""Emit a C file that checks every constant ween32 declares against the value
the real Windows headers give it.

ween32's promise is that a program compiles unchanged on either side, which
only holds if the numbers agree. They are copied by hand, so they can be
copied wrong: this found TVN_SELCHANGEDA off by one — it was the value of
TVN_SELCHANGING, so an app would have acted on the selection before it
changed — and TB_ISBUTTONCHECKED sitting on TB_ISBUTTONHIDDEN's number.

A name win32 does not define at all is the other half of that promise, and
this used to miss it: every check was wrapped in `#ifdef`, so a constant only
ween32 had was skipped — and still counted, which made the total say it had
been compared. An application could then use an invented name, build here and
fail to build on Windows, which is the one thing this gate is for.

So an absent name is a failure now. The handful that are genuinely absent are
named in ABSENT below, each with the reason it is; a name reaching that
failure without a reason beside it is a conversation, not a silent pass.

Reads include/ween32.h, writes C to stdout, and says on stderr how many it
compared and how many it knowingly did not.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "..", "..", "include", "ween32.h")

# Values that are not integer expressions, or that win32 spells differently
# enough that comparing the text is meaningless.
SKIP = {"CALLBACK", "WINAPI", "APIENTRY", "CONST", "FAR", "NEAR", "PASCAL",
        "VOID", "IN", "OUT", "OPTIONAL"}

# Constants the real headers do not define, and why. Everything else must be
# there. These are still compared wherever they do turn up, so a reason that
# stops being true costs nothing and a name that leaves ween32.h is reported
# rather than left sitting here.
#
# The first five: 64-bit win32 defines them and then takes them straight back,
# `#undef GWL_WNDPROC` and its neighbours under `#ifdef _WIN64` in winuser.h,
# because a pointer no longer fits where a LONG did. The GWLP_/DWLP_ forms are
# what exist there, and x86_64 is what this gate builds for.
ABSENT = {
    "GWL_WNDPROC": "undefined on 64-bit win32; GWLP_WNDPROC is the one there",
    "GWL_USERDATA": "undefined on 64-bit win32; GWLP_USERDATA is the one there",
    "DWL_DLGPROC": "undefined on 64-bit win32; DWLP_DLGPROC is the one there",
    "DWL_MSGRESULT": "undefined on 64-bit win32; DWLP_MSGRESULT is the one there",
    "DWL_USER": "undefined on 64-bit win32; DWLP_USER is the one there",
    # Real, and 0x3021 is the number the Microsoft SDK's prsht.h gives it, but
    # mingw-w64 has never carried it and mingw-w64 is the header set this
    # compiles against. Including prsht.h does not help: commctrl.h already
    # pulls it in, which is why PSN_APPLY and the PSH_ flags are compared.
    "IDD_APPLYNOW": "in the Microsoft SDK's prsht.h, absent from mingw-w64",
}


def main():
    body = open(HEADER, encoding="utf-8").read().split("#else", 1)[1]
    out = ["/* Generated by tools/win32check/genconsts.py — do not edit. */",
           "#include <windows.h>",
           "#include <commctrl.h>"]
    compared, absent = 0, []
    for m in re.finditer(r"^#define\s+([A-Z][A-Z0-9_]{2,})\s+(.+?)\s*(?:/\*.*)?$",
                         body, re.M):
        name, val = m.group(1), m.group(2).strip()
        if name in SKIP or name.startswith("WEEN"):
            continue
        if not re.fullmatch(r"[-+*/()\s0-9A-Za-z_ULul]+", val):
            continue          # not an integer expression
        if re.search(r"\bsizeof\b", val):
            continue
        check = ('_Static_assert((long long)(%s) == (long long)(%s), "%s");'
                 % (name, val, name))
        if name in ABSENT:
            # Known missing: compare it anyway wherever it is not.
            out += ["/* %s: %s */" % (name, ABSENT[name]),
                    "#ifdef %s" % name, check, "#endif"]
            absent.append(name)
            continue
        out += ["#ifndef %s" % name,
                '#error "%s: ween32 declares it, the real headers do not. '
                'If that is right, name it in ABSENT in '
                'tools/win32check/genconsts.py with the reason."' % name,
                "#else", check, "#endif"]
        compared += 1
    out.append("int main(void) { return 0; }")
    print("\n".join(out))

    stale = sorted(set(ABSENT) - set(absent))
    if stale:
        print("genconsts: ABSENT names ween32.h no longer declares, so the "
              "reason beside each is now unread: %s" % ", ".join(stale),
              file=sys.stderr)
        return 1
    print("/* %d constants compared against the real headers */" % compared,
          file=sys.stderr)
    print("/* %d known absent, and why, in genconsts.py: %s */"
          % (len(absent), ", ".join(sorted(absent))), file=sys.stderr)
    return 0


sys.exit(main())
