#!/usr/bin/env python3
"""Emit a C file that checks every constant ween32 declares against the value
the real Windows headers give it.

ween32's promise is that a program compiles unchanged on either side, which
only holds if the numbers agree. They are copied by hand, so they can be
copied wrong: this found TVN_SELCHANGEDA off by one — it was the value of
TVN_SELCHANGING, so an app would have acted on the selection before it
changed — and TB_ISBUTTONCHECKED sitting on TB_ISBUTTONHIDDEN's number.

Reads include/ween32.h, writes C to stdout. Constants win32 does not have are
skipped, so this only ever compares things both sides define.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "..", "..", "include", "ween32.h")

# Values that are not integer expressions, or that win32 spells differently
# enough that comparing the text is meaningless.
SKIP = {"CALLBACK", "WINAPI", "APIENTRY", "CONST", "FAR", "NEAR", "PASCAL",
        "VOID", "IN", "OUT", "OPTIONAL"}


def main():
    body = open(HEADER, encoding="utf-8").read().split("#else", 1)[1]
    print("/* Generated by tools/win32check/genconsts.py — do not edit. */")
    print("#include <windows.h>")
    print("#include <commctrl.h>")
    n = 0
    for m in re.finditer(r"^#define\s+([A-Z][A-Z0-9_]{2,})\s+(.+?)\s*(?:/\*.*)?$",
                         body, re.M):
        name, val = m.group(1), m.group(2).strip()
        if name in SKIP or name.startswith("WEEN"):
            continue
        if not re.fullmatch(r"[-+*/()\s0-9A-Za-z_ULul]+", val):
            continue          # not an integer expression
        if re.search(r"\bsizeof\b", val):
            continue
        print("#ifdef %s" % name)
        print('_Static_assert((long long)(%s) == (long long)(%s), "%s");'
              % (name, val, name))
        print("#endif")
        n += 1
    print("int main(void) { return 0; }")
    print("/* %d constants checked */" % n, file=sys.stderr)


main()
