//! Generated by tools/paint/genart.py from assets/paint-about.png.
//! One character per pixel; ' ' is the transparent colour.

pub const cell_w = 32;
pub const cell_h = 32;
pub const count = 1;

pub const palette = [_]struct { ch: u8, rgb: u32 }{
    .{ .ch = ' ', .rgb = 0xD4D0C8 }, // transparent
    .{ .ch = '#', .rgb = 0x000000 }, // 
    .{ .ch = '.', .rgb = 0xC0C0C0 }, // 
    .{ .ch = '0', .rgb = 0x969696 }, // 
    .{ .ch = '1', .rgb = 0x4D4D4D }, // 
    .{ .ch = '2', .rgb = 0xF1F1F1 }, // 
    .{ .ch = 'a', .rgb = 0x666666 }, // 
    .{ .ch = 'b', .rgb = 0x868686 }, // 
    .{ .ch = 'c', .rgb = 0x5F5F5F }, // 
    .{ .ch = 'd', .rgb = 0x555555 }, // 
    .{ .ch = 'e', .rgb = 0x777777 }, // 
    .{ .ch = 'f', .rgb = 0xF8F8F8 }, // 
    .{ .ch = 'g', .rgb = 0x008080 }, // 
    .{ .ch = 'h', .rgb = 0x000080 }, // 
    .{ .ch = 'i', .rgb = 0x800080 }, // 
    .{ .ch = 'j', .rgb = 0xFF00FF }, // 
    .{ .ch = 'k', .rgb = 0x800000 }, // 
    .{ .ch = 'l', .rgb = 0x00CCFF }, // 
    .{ .ch = 'm', .rgb = 0xFF0000 }, // 
    .{ .ch = 'n', .rgb = 0x808000 }, // 
    .{ .ch = 'o', .rgb = 0x0000FF }, // 
    .{ .ch = 'p', .rgb = 0xFFFF00 }, // 
    .{ .ch = 'q', .rgb = 0xB2B2B2 }, // 
    .{ .ch = 'r', .rgb = 0xCCCCCC }, // 
    .{ .ch = 't', .rgb = 0xEAEAEA }, // 
    .{ .ch = 'u', .rgb = 0xE3E3E3 }, // 
    .{ .ch = 'v', .rgb = 0xDDDDDD }, // 
    .{ .ch = 'x', .rgb = 0xD7D7D7 }, // 
    .{ .ch = 'y', .rgb = 0xA0A0A4 }, // 
    .{ .ch = 'z', .rgb = 0x999999 }, // 
};

pub const rows = [_][]const u8{
    "                 aba#           ",
    "            aba# c###           ",
    " b#         d### ####           ",
    "b.##        #### bbe#           ",
    " b###       bbe# bfb#           ",
    "  bfb#      bfb# b.b#           ",
    " b#b.##     b.b# gegh   aa      ",
    "b.##iji#    kbk# glgh  a#e# aa  ",
    " bb##iji#   kmk# glgh b#### db# ",
    "  bfb#iji#  kmk# glghbfb## bf## ",
    "   b.#hiji# kmk# glgn..b# b.b#  ",
    "    hgohiji#kmk# gbnpbe# hgb#   ",
    "     hgohiiikmk# gnpqn# hgoh    ",
    "      hgohiikmk# np.n# hgoh     ",
    "       hhhh#km##n..n# hgoh      ",
    "      bbbbbbbbbbbbbbbbbbbb      ",
    "     brfffftuvx..qyyz0bea1#     ",
    "     brfffftuvxr.qqyz0bea1#     ",
    "     brfffftuvrr.qqyz0bea1#     ",
    "     b.qyyeaaaaaaaaaaaaa###     ",
    "      brtttttxxqqybbeeac1#      ",
    "      brttttttxrqyzbeeac1#      ",
    "      brfffff2uxrqzzbeac1#      ",
    "      brfffff2tv..qybeac1#      ",
    "      brfffff2uvrqqyzbac1#      ",
    "      brfffff2uvr.qyzbec1#      ",
    "      brfffff2uvr.qyzbec1#      ",
    "      brfffff2uvrqqyzbbc1#      ",
    "      brfffff2uxr.qyzbbc1#      ",
    "      brfffff2uvr.qyzbec1#      ",
    "      bebbbbbbbeaaaaaaaaa#      ",
    "       ##################       ",
};
