//! Generated by tools/paint/genart.py from assets/paint-fonts.png.
//! One character per pixel; ' ' is the transparent colour.

pub const cell_w = 16;
pub const cell_h = 16;
pub const count = 4;

pub const palette = [_]struct { ch: u8, rgb: u32 }{
    .{ .ch = ' ', .rgb = 0xD4D0C8 }, // transparent
    .{ .ch = '#', .rgb = 0x000000 }, // 
    .{ .ch = 'W', .rgb = 0xFFFFFF }, // 
    .{ .ch = 's', .rgb = 0x808080 }, // 
};

pub const rows = [_][]const u8{
    "                                                                ",
    "                                                                ",
    "                                                                ",
    "   #######             #####       ###  ##       ssssssssss     ",
    "    ### ###             ##          ##  ##       sWWWWWWWWss    ",
    "    ### ###            ##           ##  ##       sW s s s sWs   ",
    "    ### ###            ##           ##  ##       sW sWsWsWssss  ",
    "    ######            ##            ##  ##       sW sWsWsW WWsW ",
    "    ### ###           ##            ######       sW sWsWsWs  sW ",
    "    ### ###          ##              #####       sW sWsWsWsW sW ",
    "    ### ###          ##                          sW  W W W W sW ",
    "   #######         #####            ######       sssssssssssssW ",
    "                                                  WWWWWWWWWWWWW ",
    "                                                                ",
    "                                                                ",
    "                                                                ",
};
