#!/usr/bin/env python3
"""Turn include/ween32.h's #defines into the Zig module's constants.

The Zig bindings and the C header declare the same API, and the one thing
that cannot be allowed to drift between them is the numbers: a constant
copied wrong is a bug that compiles, links and runs, and shows up as a
message that never arrives. `make win32` already checks the C header's
values against the real Windows SDK, so deriving the Zig side from the C
side inherits that check rather than needing a second one.

    tools/zigbind/genconsts.py include/ween32.h > /tmp/consts.zig

Object-like defines only: anything with parentheses after the name is a
macro and is hand-written on the Zig side as an inline function.
"""
import re
import sys

# A value we can hand to Zig as-is: numbers, previously defined names, and
# the operators the header actually uses to combine them.
TOKEN = re.compile(r"""
    (?P<hex>0[xX][0-9a-fA-F]+[uUlL]*)
  | (?P<dec>\d+[uUlL]*)
  | (?P<name>[A-Za-z_][A-Za-z0-9_]*)
  | (?P<op>[|&+\-~()<>*/]+)
  | (?P<space>\s+)
""", re.X)

SKIP = {
    # Types and things that are not constants at all.
    "WEEN32_H", "TRUE", "FALSE", "CALLBACK", "WINAPI", "CONST",
}


def convert(value, known):
    """The C value as Zig source, or None if it is not a plain constant."""
    out = []
    pos = 0
    while pos < len(value):
        m = TOKEN.match(value, pos)
        if not m:
            return None
        pos = m.end()
        if m.group("space"):
            out.append(" ")
        elif m.group("hex"):
            out.append(m.group("hex").rstrip("uUlL"))
        elif m.group("dec"):
            out.append(m.group("dec").rstrip("uUlL"))
        elif m.group("name"):
            if m.group("name") not in known:
                return None
            out.append(m.group("name"))
        else:
            op = m.group("op")
            if any(c in op for c in "*/"):
                return None
            out.append(op)
    text = "".join(out).strip()
    return text or None


def main(path):
    known = set()
    lines = []
    text = open(path).read()
    # Only the non-Windows half of the header declares anything; the Windows
    # half is one #include.
    body = text.split("#else", 1)[1] if "#else" in text else text
    for line in body.splitlines():
        m = re.match(r"\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.*?)\s*$", line)
        if not m:
            continue
        name, value = m.group(1), m.group(2)
        if name in SKIP or "\\" in value or not value:
            continue
        value = re.sub(r"/\*.*?\*/", "", value).strip()
        zig = convert(value, known)
        if zig is None:
            continue
        known.add(name)
        lines.append("pub const %s = %s;" % (name, zig))
    return lines


BANNER = [
    "// Generated by tools/zigbind/genconsts.py from include/ween32.h.",
    "// Every value comes from the C header, which `make win32` checks",
    "// against the real Windows SDK -- so these agree with Windows too.",
    "",
]

if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    header = args[0] if args else "include/ween32.h"
    body = BANNER + main(header)
    if "--merge" in sys.argv:
        # Rewrite the block between the markers in the Zig module, in place.
        target = args[1] if len(args) > 1 else "zig/ween32.zig"
        text = open(target).read()
        head, _, rest = text.partition("// >>> genconsts\n")
        _, _, tail = rest.partition("// <<< genconsts\n")
        open(target, "w").write(head + "// >>> genconsts\n" +
                                "\n".join(body) + "\n" +
                                "// <<< genconsts\n" + tail)
        print("%s: %d constants" % (target, len(body) - len(BANNER)))
    else:
        for l in body:
            print(l)
