#!/usr/bin/env python3
"""Generate the tool-settings art from captures of the real Paint.

The box under the tool box holds a different set of settings for each tool —
five line widths, twelve brush shapes, four rubber sizes, three fill styles —
and each one is a little picture that changes when it is the chosen one. The
chosen one is drawn on the selection navy; some flip their ink to white with
it and some, being colour pictures, do not.

Rather than describe each of those, this takes one screenshot of the box per
setting, with that setting chosen, and works out from them both where each
setting sits and what it looks like in either state:

  * the pixels that change when a setting is chosen are that setting's
    rectangle -- which is also where a click on it lands;
  * that rectangle out of its own screenshot is the picture to draw when it
    is chosen, and out of any other screenshot the picture to draw when it
    is not.

Nothing is interpreted, so a colour picture and a one-bit glyph need no
distinction, and neither does whatever Paint does at the edges.

    tools/paint/genoptions.py \\
        line tools/refcapture/paint/opt-line-*.png -- \\
        brush tools/refcapture/paint/opt-brush-*.png > art_options.zig
"""
import sys
from PIL import Image

NAVY = (10, 36, 106)
PREFERRED = {
    (212, 208, 200): " ",
    (0, 0, 0): "#",
    (255, 255, 255): "W",
    (128, 128, 128): "s",
    (10, 36, 106): "N",
    (192, 192, 192): ".",
}
SPARE = "abcdefghijklmopqrtuvxyz0123456789"


def load(path):
    im = Image.open(path).convert("RGB")
    return im, im.load(), im.size


def rect_of(sel, ref, size):
    """Where the picture that changed sits: the navy behind it, grown out
    over anything else that changed at its edge -- a glyph that reaches the
    edge of its own highlight would otherwise be cut off."""
    w, h = size
    pts = [(x, y) for y in range(h) for x in range(w) if sel[x, y] == NAVY]
    if not pts:
        pts = [(x, y) for y in range(h) for x in range(w) if sel[x, y] != ref[x, y]]
    x0 = min(p[0] for p in pts)
    x1 = max(p[0] for p in pts)
    y0 = min(p[1] for p in pts)
    y1 = max(p[1] for p in pts)

    def changed(xs, ys):
        return any(sel[x, y] != ref[x, y] for x in xs for y in ys
                   if 0 <= x < w and 0 <= y < h)

    grew = True
    while grew:
        grew = False
        if y0 > 0 and changed(range(x0, x1 + 1), [y0 - 1]):
            y0 -= 1
            grew = True
        if y1 < h - 1 and changed(range(x0, x1 + 1), [y1 + 1]):
            y1 += 1
            grew = True
        if x0 > 0 and changed([x0 - 1], range(y0, y1 + 1)):
            x0 -= 1
            grew = True
        if x1 < w - 1 and changed([x1 + 1], range(y0, y1 + 1)):
            x1 += 1
            grew = True
    return x0, y0, x1 - x0 + 1, y1 - y0 + 1


def picture(px, rect, palette):
    x0, y0, w, h = rect
    rows = []
    for y in range(y0, y0 + h):
        line = ""
        for x in range(x0, x0 + w):
            c = px[x, y]
            if c not in palette:
                palette[c] = PREFERRED.get(c) or SPARE[len(palette) % len(SPARE)]
            line += palette[c]
        rows.append(line)
    return rows


def group(name, paths, out, palette):
    ims = [load(p) for p in paths]
    size = ims[0][2]
    n = len(ims)
    out.append("pub const %s = [_]Option{" % name)
    for i in range(n):
        ref = ims[(i + 1) % n][1]
        rect = rect_of(ims[i][1], ref, size)
        on = picture(ims[i][1], rect, palette)
        off = picture(ref, rect, palette)
        out.append("    .{")
        out.append("        .x = %d, .y = %d, .w = %d, .h = %d," % rect)
        out.append("        .off = &.{")
        for r in off:
            out.append('            "%s",' % r)
        out.append("        },")
        out.append("        .on = &.{")
        for r in on:
            out.append('            "%s",' % r)
        out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")


def main(argv):
    groups = []
    cur = None
    for a in argv:
        if a == "--":
            cur = None
        elif cur is None:
            cur = [a, []]
            groups.append(cur)
        else:
            cur[1].append(a)

    palette = {}
    body = []
    for name, paths in groups:
        group(name, paths, body, palette)

    out = []
    out.append("//! Generated by tools/paint/genoptions.py from screenshots of")
    out.append("//! Windows 2000's Paint, one per setting. Do not edit: capture")
    out.append("//! the box again and re-run it.")
    out.append("")
    out.append("/// One setting: where it sits in the box, and the two pictures.")
    out.append("pub const Option = struct {")
    out.append("    x: i32,")
    out.append("    y: i32,")
    out.append("    w: i32,")
    out.append("    h: i32,")
    out.append("    off: []const []const u8,")
    out.append("    on: []const []const u8,")
    out.append("};")
    out.append("")
    out.append("pub const palette = [_]struct { ch: u8, rgb: u32 }{")
    for c, ch in sorted(palette.items(), key=lambda kv: kv[1]):
        out.append("    .{ .ch = '%s', .rgb = 0x%02X%02X%02X }," % (ch, c[0], c[1], c[2]))
    out.append("};")
    out.append("")
    return "\n".join(out + body) + "\n"


sys.stdout.write(main(sys.argv[1:]))
