//! Generated by tools/mspaint/genart.py from assets/paint-icon.png.
//! One character per pixel; ' ' is the transparent colour.

pub const cell_w = 16;
pub const cell_h = 16;
pub const count = 1;

pub const palette = [_]struct { ch: u8, rgb: u32 }{
    .{ .ch = ' ', .rgb = 0xD4D0C8 }, // transparent
    .{ .ch = '#', .rgb = 0x000000 }, // 
    .{ .ch = '.', .rgb = 0xC0C0C0 }, // 
    .{ .ch = 'a', .rgb = 0x868686 }, // 
    .{ .ch = 'b', .rgb = 0xF8F8F8 }, // 
    .{ .ch = 'c', .rgb = 0x666666 }, // 
    .{ .ch = 'd', .rgb = 0xCCCCCC }, // 
    .{ .ch = 'e', .rgb = 0xB2B2B2 }, // 
    .{ .ch = 'f', .rgb = 0xFF0000 }, // 
    .{ .ch = 'g', .rgb = 0x800000 }, // 
    .{ .ch = 'h', .rgb = 0x808000 }, // 
    .{ .ch = 'i', .rgb = 0xFFFF00 }, // 
    .{ .ch = 'j', .rgb = 0x000080 }, // 
    .{ .ch = 'k', .rgb = 0x0000FF }, // 
    .{ .ch = 'l', .rgb = 0xCC0066 }, // 
    .{ .ch = 'm', .rgb = 0x4D4D4D }, // 
    .{ .ch = 'n', .rgb = 0x777777 }, // 
    .{ .ch = 'o', .rgb = 0x393939 }, // 
    .{ .ch = 'p', .rgb = 0x424242 }, // 
    .{ .ch = 'q', .rgb = 0x999999 }, // 
    .{ .ch = 'r', .rgb = 0xA0A0A4 }, // 
    .{ .ch = 't', .rgb = 0xEAEAEA }, // 
    .{ .ch = 'u', .rgb = 0xD7D7D7 }, // 
    .{ .ch = 'v', .rgb = 0xE3E3E3 }, // 
};

pub const rows = [_][]const u8{
    "  aaaaaaaaaaa   ",
    "  abbc#dbbbbaa  ",
    "  abbeadbbbbaba ",
    "c#abbaadbbcb####",
    "ca#.bfgdba##ddd#",
    " ae#.fgdhi#dbdd#",
    "  jk#lghi#ddbbd#",
    "  ajjghi#ddbbbd#",
    "maanaanaaodbbbd#",
    "pdbbbb.eapdbbbd#",
    " peeqrcnoddbbbd#",
    " pttueqapddbbbd#",
    " pvbtuqaoddbbbd#",
    " ptbvdeapddbbbd#",
    " ptbvdeq#dddddd#",
    "  ##############",
};
