//! Generated by tools/mspaint/genart.py from assets/paint-stretch.png.
//! One character per pixel; ' ' is the transparent colour.

pub const cell_w = 32;
pub const cell_h = 32;
pub const count = 4;

pub const palette = [_]struct { ch: u8, rgb: u32 }{
    .{ .ch = ' ', .rgb = 0xD4D0C8 }, // transparent
    .{ .ch = '#', .rgb = 0x000000 }, // 
    .{ .ch = '.', .rgb = 0xC0C0C0 }, // 
    .{ .ch = 'W', .rgb = 0xFFFFFF }, // 
    .{ .ch = 'a', .rgb = 0xFF0000 }, // 
    .{ .ch = 's', .rgb = 0x808080 }, // 
};

pub const rows = [_][]const u8{
    "                                 sssssssssssssssssss#                                                           s#              ",
    "         a            a          sWWWWWWWWWWWWWWWWW.#                                                          s.#              ",
    "        aa            aa         sWWWWWWWWWWWWWWWWW.#                                                         sW.#              ",
    "       aaa            aaa        sWWWWWWWWWWWWWWWWW.#                    a            a                      sWW.#              ",
    "      aaaaaaaaaaaaaaaaaaaa       sWWWWWWWWWWWWWWWWW.#                   aa            aa                    sWWW.#      a       ",
    "       aaa            aaa        sWWWWWWWWWWWWWWWWW.#                  aaa            aaa                  sWWWW.#     aaa      ",
    "        aa            aa         sWWWWWWWWWWWWWWWWW.#      a          aaaaaaaaaaaaaaaaaaaa                sWWWWW.#    aaaaa     ",
    "         a            a          sWWWWWWWWWWWWWWWWW.#     aaa          aaa            aaa                sWWWWWW.#   aaaaaaa    ",
    "                                 sWWWWWWWWWWWWWWWWW.#    aaaaa          aa            aa                sWWWWWWW.#      a       ",
    "                                 sWWWWWWWWWWWWWWWWW.#   aaaaaaa          a            a                sWWWWWWWW.#      a       ",
    "sssssssssssssssssssssssssssssss# sWWWWWWWWWWWWWWWWW.#      a                                          sWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                                         sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                                         sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                   ssssssssssssssss#     sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                  sWWWWWWWWWWWWWWW.#     sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                 sWWWWWWWWWWWWWWW.#      sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a                sWWWWWWWWWWWWWWW.#       sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a               sWWWWWWWWWWWWWWW.#        sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a              sWWWWWWWWWWWWWWW.#         sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a             sWWWWWWWWWWWWWWW.#          sWWWWWWWWWW.#      a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a            sWWWWWWWWWWWWWWW.#           sWWWWWWWWW.#    aaaaaaa    ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a           sWWWWWWWWWWWWWWW.#            sWWWWWWWW.#      aaaaa     ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#   aaaaaaa       sWWWWWWWWWWWWWWW.#             sWWWWWWW.#        aaa      ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#    aaaaa       sWWWWWWWWWWWWWWW.#              sWWWWWW.#          a       ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#     aaa       sWWWWWWWWWWWWWWW.#               sWWWWW.#                   ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#      a       sWWWWWWWWWWWWWWW.#                sWWWW.#                    ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#             sWWWWWWWWWWWWWWW.#                 sWWW.#                     ",
    "sWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.# sWWWWWWWWWWWWWWWWW.#            sWWWWWWWWWWWWWWW.#                  sWW.#                      ",
    "s..............................# sWWWWWWWWWWWWWWWWW.#           s................#                   sW.#                       ",
    "################################ sWWWWWWWWWWWWWWWWW.#           #################                    s.#                        ",
    "                                 s..................#                                                s#                         ",
    "                                 ####################                                                #                          ",
};
