/* bake_marlett — generate the caption-glyph bitmaps in src/marlett.c from
 * fonts/marlett.ttf.
 *
 * Wine's DrawFrameControl (dlls/user32/uitools.c, UITOOLS95_DrawFrameCaption)
 * draws the caption glyphs with the Marlett font selected at -SmallDiam and a
 * centred TextOut. On an X11 desktop that text lands in FreeType's monochrome
 * rasteriser (Xft "antialias=false"); the user-validated win2k_popup_wine
 * reference (zc_new.png) is exactly that: Marlett at 12 ppem, mono, ink
 * centred on the button.
 *
 * This tool reproduces that pipeline with FreeType and emits the C table —
 * run it after swapping fonts/marlett.ttf and paste the output into
 * src/marlett.c (`baked12[]`). Build-time tool only; the library itself
 * stays dependency-free:
 *
 *   cc -std=c99 $(pkg-config --cflags --libs freetype2) tools/bake_marlett.c
 */

#include <ft2build.h>
#include FT_FREETYPE_H

#include <stdio.h>

#define PPEM 12

static const struct {
    int code;
    const char *name;
} glyphs[] = {
    { 0x72, "close 'r'" },
    { 0x30, "minimize '0'" },
    { 0x31, "maximize '1'" },
    { 0x32, "restore '2'" },
};

int main(int argc, char **argv)
{
    const char *font = argc > 1 ? argv[1] : "fonts/marlett.ttf";
    FT_Library lib;
    FT_Face face;
    if (FT_Init_FreeType(&lib) || FT_New_Face(lib, font, 0, &face)) {
        fprintf(stderr, "cannot open %s\n", font);
        return 1;
    }
    /* Marlett has no Unicode cmap (Mac-Roman + MS-Symbol only), so FreeType
     * selects no charmap by default; codes may also live at 0xF000|c. */
    if (FT_Select_Charmap(face, FT_ENCODING_APPLE_ROMAN) &&
        FT_Select_Charmap(face, FT_ENCODING_MS_SYMBOL) &&
        face->num_charmaps > 0)
        FT_Set_Charmap(face, face->charmaps[0]);
    FT_Set_Pixel_Sizes(face, 0, PPEM);

    printf("/* Generated by tools/bake_marlett.c from %s at %d ppem\n"
           " * (FreeType monochrome — the Wine/Xft caption pipeline). */\n",
           font, PPEM);
    printf("static const ween_baked_glyph baked12[] = {\n");

    for (size_t g = 0; g < sizeof(glyphs) / sizeof(glyphs[0]); g++) {
        FT_UInt gi = FT_Get_Char_Index(face, (FT_ULong)glyphs[g].code);
        if (!gi)
            gi = FT_Get_Char_Index(face, 0xF000u | (FT_ULong)glyphs[g].code);
        if (!gi ||
            FT_Load_Glyph(face, gi, FT_LOAD_TARGET_MONO | FT_LOAD_RENDER)) {
            fprintf(stderr, "cannot render 0x%02x\n", glyphs[g].code);
            continue;
        }
        FT_Bitmap *b = &face->glyph->bitmap;
        int w = (int)b->width, h = (int)b->rows;
        if (w < 1 || w > 16 || h < 1 || h > 12) {
            fprintf(stderr, "0x%02x: unexpected size %dx%d\n", glyphs[g].code,
                    w, h);
            continue;
        }
        printf("    /* %s 0x%02x */\n    { 0x%02x, %d, %d,\n      { ",
               glyphs[g].name, glyphs[g].code, glyphs[g].code, w, h);
        for (int y = 0; y < 12; y++) {
            unsigned v = 0;
            if (y < h)
                for (int x = 0; x < w; x++)
                    if (b->buffer[y * b->pitch + x / 8] & (0x80 >> (x % 8)))
                        v |= 1u << (w - 1 - x);
            printf("0x%03X%s", v, y < 11 ? ", " : " } },\n");
            if (y == 7)
                printf("\n        ");
        }
    }
    printf("};\n");
    FT_Done_Face(face);
    FT_Done_FreeType(lib);
    return 0;
}
