/* The sizing cursors, cut out of screenshots of the machine.
 *
 * Generated by tools/refcapture/cursorart.py -- do not edit. '#' is black,
 * 'W' is white and '.' is what shows through; the numbers after each are
 * the hot spot, which is where the pointer was when the shot was taken.
 *
 * X's cursor font has no double-headed diagonal arrow at all, so without
 * these a picture sized by its corner shows a corner bracket pointing
 * the wrong way.
 */

#include <stdlib.h>

#include "ween_internal.h"

/* sizenwse: 13x13, hot spot 6,6 */
static const char *const sizenwse_rows[13] = {
    "WWWWWWW......",
    "W#####W......",
    "W####W.......",
    "W###W........",
    "W##W#W.......",
    "W#W.W#W......",
    "WW...W#W...WW",
    "......W#W.W#W",
    ".......W#W##W",
    "........W###W",
    ".......W####W",
    "......W#####W",
    "......WWWWWWW",
};

/* sizewe: 19x9, hot spot 9,5 */
static const char *const sizewe_rows[9] = {
    "....WW.......WW....",
    "...W#W.......W#W...",
    "..W##W.......W##W..",
    ".W###WWWWWWWWW###W.",
    "W#################W",
    ".W###WWWWWWWWW###W.",
    "..W##W.......W##W..",
    "...W#W.......W#W...",
    "....WW.......WW....",
};

/* sizens: 9x17, hot spot 4,8 */
static const char *const sizens_rows[17] = {
    "....W....",
    "...W#W...",
    "..W###W..",
    ".W#####W.",
    "W#######W",
    "WWWW#WWWW",
    "...W#W...",
    "...W#W...",
    "...W#W...",
    "...W#W...",
    "...W#W...",
    "WWWW#WWWW",
    "W#######W",
    ".W#####W.",
    "..W###W..",
    "...W#W...",
    "....W....",
};

/* sizeall: 18x18, hot spot 9,10 */
static const char *const sizeall_rows[18] = {
    "........WW........",
    ".......W##W.......",
    "......W####W......",
    ".....W######W.....",
    ".....WWW##WWW.....",
    "...WW..W##W..WW...",
    "..W#W..W##W..W#W..",
    ".W##WWWW##WWWW##W.",
    "W################W",
    "W################W",
    ".W##WWWW##WWWW##W.",
    "..W#W..W##W..W#W..",
    "...WW..W##W..WW...",
    ".....WWW##WWW.....",
    ".....W######W.....",
    "......W####W......",
    ".......W##W.......",
    "........WW........",
};

/* One of them as pixels: black and white where the rows say so, and
 * nothing at all where they do not. */
static ween_cursor *build(const char *const *rows, int w, int h,
                          int hx, int hy, int mirror)
{
    ween_cursor *c = calloc(1, sizeof(*c));
    if (!c)
        return NULL;
    c->argb = calloc((size_t)w * (size_t)h, sizeof(unsigned));
    if (!c->argb) {
        free(c);
        return NULL;
    }
    c->magic = WEEN_CURSOR_MAGIC;
    c->w = w;
    c->h = h;
    c->xhot = mirror ? w - 1 - hx : hx;
    c->yhot = hy;
    for (int y = 0; y < h; y++)
        for (int x = 0; x < w; x++) {
            char ch = rows[y][mirror ? w - 1 - x : x];
            c->argb[y * w + x] = ch == '#'   ? 0xff000000u
                                 : ch == 'W' ? 0xffffffffu
                                             : 0u;
        }
    return c;
}

/* The one USER32 draws for a shape, or null where ween32 has none and the
 * window system's own will have to do. The other diagonal is this one
 * mirrored, which is what it is on the machine. */
const ween_cursor *ween_stock_cursor(int shape)
{
    static ween_cursor *made[WEEN_CURSOR_COUNT];
    static int done;
    if (!done) {
        done = 1;
        made[WEEN_CURSOR_SIZENWSE] = build(sizenwse_rows, 13, 13, 6, 6, 0);
        made[WEEN_CURSOR_SIZEWE] = build(sizewe_rows, 19, 9, 9, 5, 0);
        made[WEEN_CURSOR_SIZENS] = build(sizens_rows, 9, 17, 4, 8, 0);
        made[WEEN_CURSOR_SIZEALL] = build(sizeall_rows, 18, 18, 9, 10, 0);
        made[WEEN_CURSOR_SIZENESW] = build(sizenwse_rows, 13, 13, 6, 6, 1);
    }
    if (shape < 0 || shape >= WEEN_CURSOR_COUNT)
        return NULL;
    return made[shape];
}
