#!/usr/bin/env python3
"""Write tests/caption_rows.h out of the machine's caption captures.

`caption-400-machine.png` and its two neighbours are the top thirty rows of a
WordPad frame at three widths. Row 4 of each is a caption row clear of the
icon and the title, so it is the gradient and nothing else -- and that is
what tests/caption_test.c holds ween32's ramp against, column for column.

The suite has no PNG decoder and is not going to grow one for this, so the
rows are written out as C. Run this again if the captures are ever re-taken:

    tools/refcapture/caption_rows.py > tests/caption_rows.h

The row runs from the caption's left edge (the frame is four) to the last
column before the caption buttons, which on the machine is fifty-five before
the client's right edge.
"""
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
WIDTHS = (400, 500, 654)
FRAME = 4
BUTTONS = 55


def row_of(width):
    im = Image.open(os.path.join(HERE, "caption-%d-machine.png" % width))
    px = im.convert("RGB").load()
    end = width - FRAME - BUTTONS + 1  # the last ramp column, inclusive
    return [px[x, 4] for x in range(FRAME, end + 1)]


def main():
    rows = {w: row_of(w) for w in WIDTHS}
    out = sys.stdout
    out.write("/* Generated by tools/refcapture/caption_rows.py -- do not"
              " edit.\n *\n * Row 4 of the machine's own caption at three"
              " widths, from the caption's\n * left edge to the last column"
              " before its buttons. What made them is in\n * that script's"
              " header; what they are for is in tests/caption_test.c. */\n")
    out.write("struct caption_row {\n    int width;\n    int n;\n"
              "    const unsigned *px;\n};\n\n")
    for w in WIDTHS:
        out.write("static const unsigned caption_%d[] = {\n" % w)
        line = "   "
        for c in rows[w]:
            v = " 0x%02x%02x%02x," % c
            if len(line) + len(v) > 78:
                out.write(line + "\n")
                line = "   "
            line += v
        out.write(line + "\n};\n\n")
    out.write("static const struct caption_row caption_rows[] = {\n")
    for w in WIDTHS:
        out.write("    { %d, (int)(sizeof caption_%d / sizeof caption_%d[0]),"
                  " caption_%d },\n" % (w, w, w, w))
    out.write("};\n")
    sys.stderr.write("wrote %d rows, %d columns in all\n"
                     % (len(WIDTHS), sum(len(r) for r in rows.values())))


if __name__ == "__main__":
    main()
