#!/usr/bin/env python3
"""Cut the machine's sizing cursors out of screenshots of it, as C.

X's cursor font has no double-headed diagonal arrow: the nearest it offers is
a corner bracket, which is not what Windows shows and reads as the wrong
shape entirely. So the four USER32 draws are taken from the machine itself.

They were captured by filling Paint's picture with magenta and hovering the
handles that size it -- with a background that is neither black nor white,
every pixel of a cursor made of black and white can be told from what is
behind it, and the rest is transparent. The pointer's own position in each
shot is the hot spot, since that is where the cursor is anchored.

    tools/refcapture/cursorart.py > src/cursorart.c
"""
import os

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SHOTS = os.path.join(HERE, "paint")

# name, file, ink box, and where the pointer was in that shot
CURSORS = [
    ("sizenwse", "k_nwse.png", (181, 132, 193, 144), (187, 138)),
    ("sizewe", "k_we.png", (178, 87, 196, 95), (187, 92)),
    ("sizens", "k_ns.png", (122, 130, 130, 146), (126, 138)),
    ("sizeall", "k_all.png", (111, 75, 128, 92), (120, 85)),
]

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)


def rows_of(path, box, hot):
    im = Image.open(os.path.join(SHOTS, path)).convert("RGB").load()
    x0, y0, x1, y1 = box
    rows = []
    for y in range(y0, y1 + 1):
        row = ""
        for x in range(x0, x1 + 1):
            c = im[x, y]
            row += "#" if c == BLACK else ("W" if c == WHITE else ".")
        rows.append(row)
    return rows, (hot[0] - x0, hot[1] - y0)


def main():
    out = []
    out.append("/* The sizing cursors, cut out of screenshots of the machine.")
    out.append(" *")
    out.append(" * Generated by tools/refcapture/cursorart.py -- do not edit."
               " '#' is black,")
    out.append(" * 'W' is white and '.' is what shows through; the numbers"
               " after each are")
    out.append(" * the hot spot, which is where the pointer was when the shot"
               " was taken.")
    out.append(" *")
    out.append(" * X's cursor font has no double-headed diagonal arrow at all,"
               " so without")
    out.append(" * these a picture sized by its corner shows a corner bracket"
               " pointing")
    out.append(" * the wrong way.")
    out.append(" */")
    out.append("")
    out.append("#include <stdlib.h>")
    out.append("")
    out.append('#include "ween_internal.h"')
    out.append("")
    made = []
    for name, path, box, hot in CURSORS:
        rows, (hx, hy) = rows_of(path, box, hot)
        out.append("/* %s: %dx%d, hot spot %d,%d */" %
                   (name, len(rows[0]), len(rows), hx, hy))
        out.append("static const char *const %s_rows[%d] = {" % (name, len(rows)))
        for r in rows:
            out.append('    "%s",' % r)
        out.append("};")
        out.append("")
        made.append((name, len(rows[0]), len(rows), hx, hy))
    out.append("/* One of them as pixels: black and white where the rows say"
               " so, and")
    out.append(" * nothing at all where they do not. */")
    out.append("static ween_cursor *build(const char *const *rows, int w, int h,")
    out.append("                          int hx, int hy, int mirror)")
    out.append("{")
    out.append("    ween_cursor *c = calloc(1, sizeof(*c));")
    out.append("    if (!c)")
    out.append("        return NULL;")
    out.append("    c->argb = calloc((size_t)w * (size_t)h, sizeof(unsigned));")
    out.append("    if (!c->argb) {")
    out.append("        free(c);")
    out.append("        return NULL;")
    out.append("    }")
    out.append("    c->magic = WEEN_CURSOR_MAGIC;")
    out.append("    c->w = w;")
    out.append("    c->h = h;")
    out.append("    c->xhot = mirror ? w - 1 - hx : hx;")
    out.append("    c->yhot = hy;")
    out.append("    for (int y = 0; y < h; y++)")
    out.append("        for (int x = 0; x < w; x++) {")
    out.append("            char ch = rows[y][mirror ? w - 1 - x : x];")
    out.append("            c->argb[y * w + x] = ch == '#'   ? 0xff000000u")
    out.append("                                 : ch == 'W' ? 0xffffffffu")
    out.append("                                             : 0u;")
    out.append("        }")
    out.append("    return c;")
    out.append("}")
    out.append("")
    out.append("/* The one USER32 draws for a shape, or null where ween32 has"
               " none and the")
    out.append(" * window system's own will have to do. The other diagonal is"
               " this one")
    out.append(" * mirrored, which is what it is on the machine. */")
    out.append("const ween_cursor *ween_stock_cursor(int shape)")
    out.append("{")
    out.append("    static ween_cursor *made[WEEN_CURSOR_COUNT];")
    out.append("    static int done;")
    out.append("    if (!done) {")
    out.append("        done = 1;")
    for name, w, h, hx, hy in made:
        shape = {"sizenwse": "WEEN_CURSOR_SIZENWSE", "sizewe": "WEEN_CURSOR_SIZEWE",
                 "sizens": "WEEN_CURSOR_SIZENS", "sizeall": "WEEN_CURSOR_SIZEALL"}[name]
        out.append("        made[%s] = build(%s_rows, %d, %d, %d, %d, 0);"
                   % (shape, name, w, h, hx, hy))
    nw = [m for m in made if m[0] == "sizenwse"][0]
    out.append("        made[WEEN_CURSOR_SIZENESW] ="
               " build(sizenwse_rows, %d, %d, %d, %d, 1);" % (nw[1], nw[2], nw[3], nw[4]))
    out.append("    }")
    out.append("    if (shape < 0 || shape >= WEEN_CURSOR_COUNT)")
    out.append("        return NULL;")
    out.append("    return made[shape];")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
