#!/usr/bin/env python3
"""Cut the file dialog's pictures out of a capture of the machine's, as C.

The shell's Open dialog draws five 32x32 icons down its places bar, a strip
of four toolbar buttons, a folder in its "Look in" box and a document in its
list. None of them is guessable and all of them sit on a background this
library knows the colour of -- grey 128 in the places bar, the face colour in
the toolbar, white in the box and the list -- so they are taken as opaque
rectangles, exactly as the machine drew them, rather than interpreted.

    tools/refcapture/shellart.py                # reads dlg-open.png
    tools/refcapture/shellart.py > src/shellart.c

Where each rectangle is was read off the same capture and off the window tree
tools/vm/probe.c dumped; the numbers are in BOXES below.
"""
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "paint", "dlg-open.png")

# name, x, y, w, h -- in the capture, whose (0,0) is the dialog's top left
BOXES = [
    ("history", 37, 64, 32, 32),
    ("desktop", 37, 116, 32, 32),
    ("documents", 37, 168, 32, 32),
    ("computer", 37, 220, 32, 32),
    ("network", 37, 272, 32, 32),
    ("toolbar", 376, 30, 120, 23),
    ("lookin", 109, 33, 16, 16),
    ("document16", 105, 61, 16, 16),
]

# Printable characters that need no escaping in a C string, in a stable order
# so that a re-run of this produces the same file.
ALPHABET = ("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "abcdefghijklmnopqrstuvwxyz!#$%&()*+,-./:;<=>?@[]^_`{|}~")


def emit(im, name, x, y, w, h, out):
    px = im.crop((x, y, x + w, y + h)).load()
    order = []
    seen = {}
    for j in range(h):
        for i in range(w):
            c = px[i, j]
            if c not in seen:
                seen[c] = len(order)
                order.append(c)
    if len(order) > len(ALPHABET):
        sys.exit("%s: %d colours, more than the alphabet holds" %
                 (name, len(order)))
    out.append("/* %s: %dx%d out of the capture at %d,%d, %d colours */"
               % (name, w, h, x, y, len(order)))
    out.append("static const ween_color %s_pal[%d] = {" % (name, len(order)))
    line = "   "
    for c in order:
        item = " 0x%02x%02x%02x," % (c[0], c[1], c[2])
        if len(line) + len(item) > 78:
            out.append(line)
            line = "   "
        line += item
    out.append(line)
    out.append("};")
    out.append("static const char *const %s_rows[%d] = {" % (name, h))
    for j in range(h):
        row = "".join(ALPHABET[seen[px[i, j]]] for i in range(w))
        out.append('    "%s",' % row)
    out.append("};")
    out.append("")


def main():
    im = Image.open(REF).convert("RGB")
    out = []
    out.append("/* The file dialog's pictures, cut out of a capture of the "
               "machine's own.")
    out.append(" *")
    out.append(" * Generated by tools/refcapture/shellart.py -- do not edit. "
               "Each is the")
    out.append(" * rectangle the machine drew, background and all: the places "
               "bar is grey")
    out.append(" * 128, the tool bar is the face colour, the box and the list "
               "are white,")
    out.append(" * and drawing them over the same colour is what makes them "
               "exact.")
    out.append(" */")
    out.append("")
    out.append("#include <string.h>")
    out.append("")
    out.append('#include "ween_internal.h"')
    out.append("")
    for name, x, y, w, h in BOXES:
        emit(im, name, x, y, w, h, out)
    out.append("/* One character per pixel, and the character is where the")
    out.append(" * colour is in the palette. */")
    out.append("static const char alphabet[] =")
    out.append('    "%s"' % ALPHABET[:47])
    out.append('    "%s";' % ALPHABET[47:])
    out.append("")
    out.append("static void unpack(ween_color *dst, const char *const *rows,")
    out.append("                   const ween_color *pal, int w, int h)")
    out.append("{")
    out.append("    for (int y = 0; y < h; y++)")
    out.append("        for (int x = 0; x < w; x++)")
    out.append("            dst[y * w + x] =")
    out.append("                pal[(int)(strchr(alphabet, rows[y][x]) - alphabet)];")
    out.append("}")
    out.append("")
    for name, x, y, w, h in BOXES:
        out.append("static ween_color %s_px[%d];" % (name, w * h))
    out.append("")
    out.append("/* Each picture, unpacked once and kept. */")
    out.append("const ween_shell_art *ween_shell_picture(int which)")
    out.append("{")
    out.append("    static ween_shell_art art[%d];" % len(BOXES))
    out.append("    static int done;")
    out.append("    if (!done) {")
    for n, (name, x, y, w, h) in enumerate(BOXES):
        out.append("        art[%d].w = %d;" % (n, w))
        out.append("        art[%d].h = %d;" % (n, h))
        out.append("        art[%d].px = %s_px;" % (n, name))
        out.append("        unpack(%s_px, %s_rows, %s_pal, %d, %d);"
                   % (name, name, name, w, h))
    out.append("        done = 1;")
    out.append("    }")
    out.append("    if (which < 0 || which >= %d)" % len(BOXES))
    out.append("        return NULL;")
    out.append("    return &art[which];")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
