#!/usr/bin/env python3
"""Turn a picture into Zig source: a palette and one character per pixel.

Paint's tool glyphs and the little pictures in its options box are bitmap
resources in the real program. Here they are a generated Zig file — one
character per pixel against a palette, which stays greppable and diffable in
a way a committed .bmp does not, and needs no decoder at run time.

    tools/mspaint/genart.py assets/paint-tools.png tools 16 \\
        > examples/mspaint/art_tools.zig

The width argument is the width of one cell; the picture is cut into that
many-pixel-wide frames left to right.
"""
import sys
from PIL import Image

# The characters are chosen so the art reads as a picture in the source: a
# space is the transparent face colour, '#' is black, '.' light grey.
PREFERRED = {
    (212, 208, 200): " ",
    (0, 0, 0): "#",
    (192, 192, 192): ".",
    (255, 255, 255): "W",
    (128, 128, 128): "s",
    (64, 64, 64): "D",
}
SPARE = "abcdefghijklmnopqrtuvxyz0123456789"


def main(path, name, cell):
    im = Image.open(path)
    # A picture with an alpha channel says which pixels are transparent; one
    # without uses the face colour for it, which is how the tool glyphs were
    # cut out of a screenshot of the tool box.
    alpha = im.mode in ("RGBA", "LA") or "transparency" in im.info
    im = im.convert("RGBA") if alpha else im.convert("RGB")
    w, h = im.size
    px = im.load()
    if alpha:
        for y in range(h):
            for x in range(w):
                r, g, b, a = px[x, y]
                px[x, y] = (212, 208, 200, 255) if a == 0 else (r, g, b, 255)
        im = im.convert("RGB")
        px = im.load()
    palette = {}
    order = []
    for y in range(h):
        for x in range(w):
            c = px[x, y]
            if c in palette:
                continue
            ch = PREFERRED.get(c) or SPARE[len([1 for k in palette if k not in PREFERRED])]
            palette[c] = ch
            order.append((ch, c))
    order.sort()

    out = []
    out.append("//! Generated by tools/mspaint/genart.py from %s." % path)
    out.append("//! One character per pixel; ' ' is the transparent colour.")
    out.append("")
    out.append("pub const cell_w = %d;" % cell)
    out.append("pub const cell_h = %d;" % h)
    out.append("pub const count = %d;" % (w // cell))
    out.append("")
    out.append("pub const palette = [_]struct { ch: u8, rgb: u32 }{")
    for ch, c in order:
        out.append("    .{ .ch = '%s', .rgb = 0x%02X%02X%02X }, // %s"
                   % (ch, c[0], c[1], c[2], "transparent" if ch == " " else ""))
    out.append("};")
    out.append("")
    out.append("pub const rows = [_][]const u8{")
    for y in range(h):
        line = "".join(palette[px[x, y]] for x in range(w))
        out.append('    "%s",' % line)
    out.append("};")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(main(sys.argv[1], sys.argv[2], int(sys.argv[3])))
